export type Side = 'front' | 'rear' | 'left' | 'right';
export type Motion =
  | 'press_once'
  | 'hold'
  | 'double_press'
  | 'hold_and_press'
  | 'rotate'
  | 'slide'
  | 'connect'
  | 'observe';
export type Control = {
  id: string;
  label: string;
  easy: string;
  location: string;
  side: Side;
  kind: 'button' | 'knob' | 'slider' | 'port' | 'display' | 'keys';
  x: number;
  y: number;
  w: number;
  h: number;
  actualBbox: null;
};
export const MODEL_ID = 'roland_juno_ds61';
export const PROFILE_ID = 'roland_juno_ds61_demo';
export const RELEASE_ID = 'demo-2026-09-v1';
export const MANUAL_URL =
  'https://static.roland.com/assets/media/pdf/JUNO-DS_e02_W.pdf';
export const MODEL_MANUALS =
  'https://www.roland.com/global/support/by_product/juno-ds61/owners_manuals/';
export const catalog = [
  {
    id: MODEL_ID,
    brand: 'Roland',
    name: 'JUNO-DS61',
    suffix: '61',
    keys: 61,
    speaker: false,
    status: 'document_checked',
    manual: MODEL_MANUALS,
    aliases: ['JUNO DS 61', 'JUNODS61'],
  },
  {
    id: 'roland_juno_ds76',
    brand: 'Roland',
    name: 'JUNO-DS76',
    suffix: '76',
    keys: 76,
    speaker: false,
    status: 'planned',
    manual:
      'https://www.roland.com/global/support/by_product/juno-ds76/owners_manuals/',
    aliases: ['JUNODS76'],
  },
  {
    id: 'roland_juno_ds88',
    brand: 'Roland',
    name: 'JUNO-DS88',
    suffix: '88',
    keys: 88,
    speaker: false,
    status: 'planned',
    manual:
      'https://www.roland.com/global/support/by_product/juno-ds88/owners_manuals/',
    aliases: ['JUNODS88'],
  },
  {
    id: 'yamaha_modx6',
    brand: 'Yamaha',
    name: 'MODX6',
    suffix: '6',
    keys: 61,
    speaker: false,
    status: 'planned',
    manual: 'https://manual.yamaha.com/mi/synth/modx/en/',
    aliases: [],
  },
  {
    id: 'yamaha_modx6_plus',
    brand: 'Yamaha',
    name: 'MODX6+',
    suffix: '6+',
    keys: 61,
    speaker: false,
    status: 'planned',
    manual: 'https://manual.yamaha.com/mi/synth/modx/en/',
    aliases: ['MODX6 PLUS'],
  },
  {
    id: 'yamaha_modx8',
    brand: 'Yamaha',
    name: 'MODX8',
    suffix: '8',
    keys: 88,
    speaker: false,
    status: 'planned',
    manual: 'https://manual.yamaha.com/mi/synth/modx/en/',
    aliases: [],
  },
] as const;
export type Model = (typeof catalog)[number];
const c = (
  id: string,
  label: string,
  easy: string,
  location: string,
  side: Side,
  kind: Control['kind'],
  x: number,
  y: number,
  w: number,
  h: number,
): Control => ({
  id,
  label,
  easy,
  location,
  side,
  kind,
  x,
  y,
  w,
  h,
  actualBbox: null,
});
// Normalized schematic coordinates only. These are not measured hardware coordinates.
export const controls: Control[] = [
  c(
    'front.volume',
    'MASTER VOLUME',
    '전체 소리 크기',
    '전면 왼쪽 음량 노브',
    'front',
    'knob',
    0.058,
    0.24,
    0.045,
    0.12,
  ),
  c(
    'front.level',
    'LOWER LEVEL',
    '파트별 소리 크기',
    '전면 왼쪽 슬라이더 영역',
    'front',
    'slider',
    0.17,
    0.32,
    0.055,
    0.17,
  ),
  c(
    'front.display',
    'DISPLAY',
    '악기 화면',
    '전면 중앙의 표시부',
    'front',
    'display',
    0.438,
    0.18,
    0.16,
    0.14,
  ),
  c(
    'front.value',
    'VALUE',
    '소리를 고르는 큰 다이얼',
    '가운데 화면 오른쪽',
    'front',
    'knob',
    0.645,
    0.2,
    0.058,
    0.15,
  ),
  c(
    'front.split',
    'SPLIT',
    '왼손·오른손 나누기',
    'KEYBOARD 구역 첫째 줄 왼쪽',
    'front',
    'button',
    0.278,
    0.22,
    0.039,
    0.038,
  ),
  c(
    'front.dual',
    'DUAL',
    '두 소리 겹치기',
    'KEYBOARD 구역 첫째 줄 가운데',
    'front',
    'button',
    0.326,
    0.22,
    0.039,
    0.038,
  ),
  c(
    'front.super_layer',
    'SUPER LAYER',
    '같은 소리 겹치기',
    'KEYBOARD 구역 첫째 줄 오른쪽',
    'front',
    'button',
    0.374,
    0.22,
    0.039,
    0.038,
  ),
  c(
    'front.arpeggio',
    'ARPEGGIO',
    '자동 음형 연주',
    'KEYBOARD 구역 둘째 줄 왼쪽',
    'front',
    'button',
    0.278,
    0.32,
    0.039,
    0.038,
  ),
  c(
    'front.key_touch',
    'KEY TOUCH',
    '건반 터치 설정',
    'KEYBOARD 구역 둘째 줄 가운데',
    'front',
    'button',
    0.326,
    0.32,
    0.039,
    0.038,
  ),
  c(
    'front.patch',
    'PATCH/PERFORM',
    '소리 선택 모드',
    'KEYBOARD 구역 둘째 줄 오른쪽',
    'front',
    'button',
    0.374,
    0.32,
    0.039,
    0.038,
  ),
  c(
    'front.transpose',
    'TRANSPOSE',
    '반음 단위 높낮이',
    'KEYBOARD 구역 셋째 줄 왼쪽',
    'front',
    'button',
    0.278,
    0.42,
    0.039,
    0.038,
  ),
  c(
    'front.octave_down',
    'OCTAVE −',
    '한 옥타브 아래로',
    'KEYBOARD 구역 셋째 줄 가운데',
    'front',
    'button',
    0.326,
    0.42,
    0.039,
    0.038,
  ),
  c(
    'front.octave_up',
    'OCTAVE +',
    '한 옥타브 위로',
    'KEYBOARD 구역 셋째 줄 오른쪽',
    'front',
    'button',
    0.374,
    0.42,
    0.039,
    0.038,
  ),
  c(
    'front.drums',
    'DRUMS',
    '드럼 소리 종류',
    '화면 아래 카테고리 줄 첫 번째',
    'front',
    'button',
    0.432,
    0.46,
    0.026,
    0.036,
  ),
  c(
    'front.piano',
    'PIANO',
    '피아노 소리 종류',
    '화면 아래 카테고리 줄 왼쪽에서 두 번째',
    'front',
    'button',
    0.462,
    0.46,
    0.026,
    0.036,
  ),
  c(
    'front.keyboard',
    'KEYBOARD/ORGAN',
    '전자피아노와 오르간 소리',
    '화면 아래 카테고리 줄 세 번째',
    'front',
    'button',
    0.492,
    0.46,
    0.026,
    0.036,
  ),
  c(
    'front.guitar',
    'GUITAR/BASS',
    '기타와 베이스 소리 종류',
    '화면 아래 카테고리 줄 네 번째',
    'front',
    'button',
    0.522,
    0.46,
    0.026,
    0.036,
  ),
  c(
    'front.orchestra',
    'ORCHESTRA',
    '관현악기 소리 종류',
    '화면 아래 카테고리 줄 다섯 번째',
    'front',
    'button',
    0.552,
    0.46,
    0.026,
    0.036,
  ),
  c(
    'front.exit',
    'EXIT',
    '화면 나가기',
    'VALUE 아래쪽',
    'front',
    'button',
    0.644,
    0.38,
    0.028,
    0.038,
  ),
  c(
    'front.enter',
    'ENTER',
    '화면 선택 확인',
    'EXIT 오른쪽',
    'front',
    'button',
    0.68,
    0.38,
    0.028,
    0.038,
  ),
  c(
    'front.keys',
    'KEYS',
    '소리를 내는 건반',
    '전면 아래쪽',
    'front',
    'keys',
    0.055,
    0.61,
    0.89,
    0.32,
  ),
  c(
    'rear.usb_memory',
    'USB MEMORY',
    'USB 메모리 단자',
    '후면 USB 단자 영역',
    'rear',
    'port',
    0.1,
    0.43,
    0.05,
    0.13,
  ),
  c(
    'rear.usb',
    'USB COMPUTER',
    '컴퓨터 연결 단자',
    '후면 USB 단자 영역',
    'rear',
    'port',
    0.18,
    0.43,
    0.05,
    0.13,
  ),
  c(
    'rear.pedal',
    'PEDAL HOLD',
    '서스테인 페달 단자',
    '후면 페달 단자 영역',
    'rear',
    'port',
    0.37,
    0.43,
    0.05,
    0.13,
  ),
  c(
    'rear.output_r',
    'OUTPUT R',
    '오른쪽 오디오 출력',
    '후면 OUTPUT 단자 쌍',
    'rear',
    'port',
    0.51,
    0.43,
    0.05,
    0.13,
  ),
  c(
    'rear.output_l_mono',
    'OUTPUT L/MONO',
    '모노·왼쪽 오디오 출력',
    '후면 OUTPUT 단자 쌍',
    'rear',
    'port',
    0.59,
    0.43,
    0.05,
    0.13,
  ),
  c(
    'rear.phones',
    'PHONES',
    '헤드폰 연결 단자',
    '후면 PHONES 표시',
    'rear',
    'port',
    0.69,
    0.43,
    0.05,
    0.13,
  ),
  c(
    'rear.dc_in',
    'DC IN',
    '전원 어댑터 단자',
    '후면 POWER 왼쪽',
    'rear',
    'port',
    0.8,
    0.43,
    0.05,
    0.13,
  ),
  c(
    'rear.power',
    'POWER',
    '전원 스위치',
    '후면 DC IN 오른쪽',
    'rear',
    'button',
    0.9,
    0.43,
    0.038,
    0.09,
  ),
];
export type Step = {
  id: string;
  title: string;
  body: string;
  control: string;
  secondary?: string;
  motion: Motion;
  confirm: string;
  expected: string;
  sourcePage: number;
  kind: 'observe' | 'act' | 'check';
  value?: number;
  warning?: string;
};
export type Lesson = {
  id: string;
  code: string;
  title: string;
  short: string;
  description: string;
  icon: string;
  minutes: number;
  category: '기본 조작' | '소리 조합' | '높낮이';
  steps: Step[];
  result: string;
  risk: 'R0';
  recovery: string;
  sources: { url: string; page: number }[];
};
const s = (
  id: string,
  title: string,
  body: string,
  control: string,
  motion: Motion,
  expected: string,
  sourcePage = 5,
  extra: Partial<Step> = {},
): Step => ({
  id,
  title,
  body,
  control,
  motion,
  expected,
  sourcePage,
  kind: motion === 'observe' ? 'observe' : 'act',
  confirm: motion === 'observe' ? '확인했어요' : '화면에서 해 봤어요',
  ...extra,
});
const l = (
  id: string,
  code: string,
  title: string,
  short: string,
  description: string,
  icon: string,
  minutes: number,
  category: Lesson['category'],
  steps: Step[],
  result: string,
): Lesson => ({
  id,
  code,
  title,
  short,
  description,
  icon,
  minutes,
  category,
  steps,
  result,
  risk: 'R0',
  recovery: '화면 연습만 초기화합니다. 실제 악기 상태는 바뀌지 않아요.',
  sources: [{ url: MANUAL_URL, page: steps[0].sourcePage }],
});
export const lessons: Lesson[] = [
  l(
    'first-sound',
    'L00',
    '처음 소리 내기',
    '첫 소리',
    '연결부터 음량까지, 첫 연주를 준비해요.',
    'volume',
    4,
    '기본 조작',
    [
      s(
        'low',
        '소리 크기부터 작게',
        '화면 속 MASTER VOLUME을 왼쪽으로 돌려 보세요.',
        'front.volume',
        'rotate',
        '음량 표시가 낮아졌나요?',
        3,
        {
          value: 10,
          warning:
            '이 기종에는 내장 스피커가 없어요. 헤드폰 또는 외부 스피커가 필요해요.',
        },
      ),
      s(
        'phones',
        '헤드폰 단자 찾기',
        '후면의 PHONES 단자를 눌러 보세요.',
        'rear.phones',
        'connect',
        '헤드폰 연결 위치를 찾았나요?',
        3,
      ),
      s(
        'power',
        '전원 스위치 찾기',
        '후면에서 POWER 표시를 찾아보세요.',
        'rear.power',
        'press_once',
        'POWER가 후면에 있다는 것을 확인했나요?',
        3,
      ),
      s(
        'piano',
        '피아노 버튼 누르기',
        '화면 속 PIANO 버튼을 한 번 눌러 보세요.',
        'front.piano',
        'press_once',
        '화면에 PIANO가 보이나요?',
      ),
      s(
        'up',
        '소리 크기 조금 올리기',
        '화면 속 음량을 조금만 올려 보세요.',
        'front.volume',
        'rotate',
        '음량 조절 방향을 확인했나요?',
        3,
        { value: 30 },
      ),
      s(
        'play',
        '건반 위치 확인하기',
        '화면 속 건반을 눌러 위치를 확인해 보세요.',
        'front.keys',
        'press_once',
        '첫 소리를 내는 순서를 살펴봤나요?',
        5,
        { confirm: '연습을 마쳤어요' },
      ),
    ],
    '연결 위치와 소리 크기를 조절하는 순서를 알아봤어요.',
  ),
  l(
    'piano',
    'L01',
    '피아노 소리 고르기',
    '피아노 소리',
    'PIANO 버튼과 다이얼, 두 가지만 기억해요.',
    'piano',
    3,
    '기본 조작',
    [
      s(
        'start',
        '소리 선택 화면 확인',
        '가운데 화면에서 PATCH 표시를 확인해 보세요.',
        'front.display',
        'observe',
        '예시 화면에 PATCH가 보이나요?',
        5,
        { warning: '학습용 예시입니다. 실제 저장 음색과 다를 수 있어요.' },
      ),
      s(
        'mode',
        '모드 버튼 위치 알아보기',
        '꺼진 PATCH/PERFORM 버튼 위치만 확인하세요.',
        'front.patch',
        'observe',
        '표시등이 꺼진 상태를 확인했나요?',
      ),
      s(
        'piano',
        'PIANO 버튼을 한 번',
        '밝게 표시된 PIANO 버튼을 눌러 보세요.',
        'front.piano',
        'press_once',
        '화면의 소리 종류가 PIANO로 바뀌었나요?',
      ),
      s(
        'choose',
        '돌려서 다른 피아노 찾기',
        '화면 옆 VALUE 다이얼을 돌려 보세요.',
        'front.value',
        'rotate',
        '예시 소리 이름이 바뀌었나요?',
        5,
        { value: 2 },
      ),
      s(
        'done',
        '배운 버튼을 기억해요',
        'PIANO는 소리 종류, VALUE는 그 안의 소리를 골라요.',
        'front.keys',
        'press_once',
        '두 가지 역할을 구분할 수 있나요?',
        5,
        { confirm: '구분할 수 있어요' },
      ),
    ],
    'PIANO와 VALUE로 피아노 소리를 고르는 방법을 알아봤어요.',
  ),
  l(
    'sounds',
    'L02',
    '다른 악기 소리 찾아보기',
    '소리 바꾸기',
    '전자피아노와 현악기, 새로운 소리를 찾아요.',
    'music',
    3,
    '기본 조작',
    [
      s(
        'read',
        '시작 음색 기억하기',
        '예시 화면에 표시된 PIANO를 기억해 주세요.',
        'front.display',
        'observe',
        '연습 시작 음색을 확인했나요?',
      ),
      s(
        'keyboard',
        '건반 소리 종류 찾기',
        'KEYBOARD/ORGAN 버튼을 눌러 보세요.',
        'front.keyboard',
        'press_once',
        '예시 소리 종류가 바뀌었나요?',
      ),
      s(
        'value',
        '다이얼로 다른 소리 찾기',
        'VALUE 다이얼을 조금 돌려 보세요.',
        'front.value',
        'rotate',
        '예시 소리 이름이 달라졌나요?',
        5,
        { value: 2 },
      ),
      s(
        'strings',
        '현악기 소리 찾아보기',
        'ORCHESTRA 버튼을 눌러 보세요.',
        'front.orchestra',
        'press_once',
        '현악기 소리 종류를 찾았나요?',
      ),
      s(
        'finish',
        '피아노 종류로 돌아가기',
        'PIANO 버튼을 눌러 화면 연습을 마쳐요.',
        'front.piano',
        'press_once',
        '연습 시작 종류로 돌아왔나요?',
      ),
    ],
    '카테고리 버튼으로 서로 다른 소리 종류를 찾아봤어요.',
  ),
  l(
    'dual',
    'L03',
    '두 소리 겹쳐 연주하기',
    '두 소리 겹치기',
    '피아노 위에 다른 소리를 더해 봐요.',
    'layers',
    4,
    '소리 조합',
    [
      s(
        'read',
        'DUAL 상태 먼저 확인',
        '화면 속 DUAL 표시등이 꺼져 있는지 보세요.',
        'front.dual',
        'observe',
        '연습 표시등이 꺼져 있나요?',
        6,
      ),
      s(
        'on',
        'DUAL 한 번 누르기',
        '화면 속 DUAL 버튼을 눌러 보세요.',
        'front.dual',
        'press_once',
        '예시 화면에 두 파트가 보이나요?',
        6,
      ),
      s(
        'parts',
        '두 파트 알아보기',
        '위아래에 표시된 두 소리 이름을 살펴보세요.',
        'front.display',
        'observe',
        'UPPER와 LOWER를 찾았나요?',
        6,
      ),
      s(
        'balance',
        '파트의 크기 알아보기',
        '화면 속 LOWER LEVEL 슬라이더를 움직여 보세요.',
        'front.level',
        'slide',
        '슬라이더의 이동 방향을 확인했나요?',
        6,
        { value: 60 },
      ),
      s(
        'off',
        '겹치기 연습 끝내기',
        '켜진 DUAL을 다시 눌러 화면 연습을 마쳐요.',
        'front.dual',
        'press_once',
        '예시 DUAL 표시등이 꺼졌나요?',
        6,
        { value: 0 },
      ),
    ],
    '두 소리를 겹치는 DUAL과 파트별 음량을 살펴봤어요.',
  ),
  l(
    'split',
    'L04',
    '왼손·오른손 소리 나누기',
    '건반 나누기',
    '건반의 양쪽을 다른 소리로 사용해요.',
    'split',
    4,
    '소리 조합',
    [
      s(
        'read',
        'SPLIT 상태 확인',
        '화면 속 SPLIT 표시등을 확인해 보세요.',
        'front.split',
        'observe',
        '연습 표시등이 꺼져 있나요?',
        6,
      ),
      s(
        'on',
        'SPLIT 버튼 누르기',
        '화면 속 SPLIT을 한 번 눌러 보세요.',
        'front.split',
        'press_once',
        '건반이 두 영역으로 나뉘었나요?',
        6,
      ),
      s(
        'keys',
        '왼손과 오른손 영역',
        '나뉜 건반을 눌러 두 영역의 위치를 알아보세요.',
        'front.keys',
        'press_once',
        'LOWER와 UPPER 위치를 확인했나요?',
        6,
      ),
      s(
        'off',
        '나누기 연습 마치기',
        '켜진 SPLIT을 다시 눌러 연습을 마쳐요.',
        'front.split',
        'press_once',
        '예시 SPLIT 표시등이 꺼졌나요?',
        6,
        { value: 0 },
      ),
    ],
    'SPLIT으로 왼손·오른손 영역을 나누는 방법을 알아봤어요.',
  ),
  l(
    'octave',
    'L05',
    '한 옥타브 높이거나 낮추기',
    '옥타브 바꾸기',
    '건반은 그대로, 소리 범위를 바꿔 봐요.',
    'octave',
    3,
    '높낮이',
    [
      s(
        'read',
        '시작값 확인하기',
        '예시 화면의 OCTAVE 시작값 0을 확인하세요.',
        'front.display',
        'observe',
        '시작값을 확인했나요?',
        6,
      ),
      s(
        'up',
        '한 옥타브 위로',
        '화면 속 OCTAVE +를 한 번 눌러 보세요.',
        'front.octave_up',
        'press_once',
        '예시 값이 +1로 바뀌었나요?',
        6,
        { value: 1 },
      ),
      s(
        'down',
        '한 옥타브 아래로',
        '화면 속 OCTAVE −를 한 번 눌러 보세요.',
        'front.octave_down',
        'press_once',
        '연습 시작값 0으로 돌아왔나요?',
        6,
        { value: 0 },
      ),
    ],
    '옥타브 버튼을 눌렀을 때 바뀌는 범위를 알아봤어요.',
  ),
  l(
    'transpose',
    'L06',
    '같은 손모양으로 높낮이 바꾸기',
    '조옮김',
    '누른 채 누르기 동작을 차근차근 익혀요.',
    'transpose',
    4,
    '높낮이',
    [
      s(
        'read',
        '변경 전 값 확인',
        '예시 화면에서 TRANSPOSE 시작값 0을 확인하세요.',
        'front.display',
        'observe',
        '연습 시작값을 확인했나요?',
        7,
        {
          warning:
            '실제 악기의 시작값을 모르면 0을 원래 값으로 가정하지 않아요.',
        },
      ),
      s(
        'hold',
        '누른 채 다른 버튼 누르기',
        'TRANSPOSE를 유지하고 OCTAVE +를 누르는 순서를 보세요.',
        'front.transpose',
        'hold_and_press',
        '유지할 버튼과 누를 버튼을 구분했나요?',
        7,
        { secondary: 'front.octave_up', value: 1 },
      ),
      s(
        'restore',
        '연습 시작값으로 돌아가기',
        'TRANSPOSE를 유지하고 OCTAVE −를 누르는 순서를 보세요.',
        'front.transpose',
        'hold_and_press',
        '예시 값이 0으로 돌아왔나요?',
        7,
        { secondary: 'front.octave_down', value: 0 },
      ),
    ],
    'TRANSPOSE를 유지하면서 높낮이를 바꾸는 동작을 알아봤어요.',
  ),
  l(
    'finish',
    'L07',
    '안전하게 연습 마치기',
    '마무리하기',
    '바꾼 값을 확인하고 학습을 마쳐요.',
    'check',
    2,
    '기본 조작',
    [
      s(
        'values',
        '바뀐 값 확인하기',
        '예시 화면에서 옥타브와 조옮김 값을 확인하세요.',
        'front.display',
        'observe',
        '현재 값을 확인했나요?',
        7,
        {
          warning:
            '실제 시작값을 모르면 담당자에게 확인하세요. 저장·초기화는 안내하지 않아요.',
        },
      ),
      s(
        'volume',
        '음량 낮추기 연습',
        '화면 속 MASTER VOLUME을 왼쪽으로 돌려 보세요.',
        'front.volume',
        'rotate',
        '연습 음량이 낮아졌나요?',
        3,
        { value: 0 },
      ),
      s(
        'complete',
        '학습 기록만 남겨요',
        '완료 기록은 이 기기에 저장돼요. 악기 설정을 저장하지 않아요.',
        'front.display',
        'observe',
        '화면 연습을 마칠까요?',
        3,
        { confirm: '안전하게 마쳤어요' },
      ),
    ],
    '시작값 확인과 음량을 낮추는 마무리 순서를 익혔어요.',
  ),
];
export const helpTopics = [
  {
    id: 'no-sound',
    title: '소리가 안 나요',
    icon: 'volume',
    intro: '소리를 듣는 장치부터 차례로 확인해요.',
    checks: [
      'JUNO-DS61에는 내장 스피커가 없어요. 헤드폰 또는 외부 스피커를 사용하는지 확인해 주세요.',
      '헤드폰은 PHONES, 외부 스피커는 OUTPUT 연결인지 표시를 확인해 주세요. 악기를 옮기거나 뒤집지 않아도 괜찮아요.',
      '실제 악기와 외부 스피커의 음량 상태를 확인해 주세요. 갑자기 크게 올리지 마세요.',
      '그래도 소리가 없으면 추가 조작을 멈추고 강사나 공식 지원에 연결해 주세요.',
    ],
    control: 'rear.phones',
  },
  {
    id: 'wrong-sound',
    title: '예상과 다른 소리가 나요',
    icon: 'piano',
    intro: '소리 종류와 겹치기·나누기 상태를 살펴봐요.',
    checks: [
      '지금 사용하는 정확한 모델명을 다시 확인해 주세요.',
      '화면의 모드, 선택 파트, 음색 이름을 확인해 주세요.',
      '선택 대상이 불명확하거나 편집 중이라면 담당자에게 확인해 주세요. 저장·초기화는 누르지 않아도 돼요.',
    ],
    control: 'front.display',
  },
  {
    id: 'pitch',
    title: '음 높이가 이상해요',
    icon: 'octave',
    intro: '조옮김과 옥타브의 현재 값을 확인해요.',
    checks: [
      '화면에 표시된 TRANSPOSE 값을 확인해 주세요.',
      'OCTAVE 값과 적용되는 파트를 확인해 주세요.',
      '시작값을 모르면 임의로 0으로 바꾸지 말고 담당자에게 확인해 주세요.',
    ],
    control: 'front.transpose',
  },
  {
    id: 'screen-different',
    title: '화면이 설명과 달라요',
    icon: 'screen',
    intro: '확인 전에는 다른 버튼을 더 누르지 않아도 괜찮아요.',
    checks: [
      '저장 확인, 처리 중, 오류, 메뉴, 연주 화면 중 어떤 상태인지 살펴봐 주세요.',
      '저장·덮어쓰기·초기화 확인이 보이면 실행하지 말고 담당자에게 확인해 주세요.',
      '지금 상태를 모르면 EXIT를 반복해서 누르지 말고 화면 연습이나 공식 설명서로 돌아가 주세요.',
    ],
    control: 'front.display',
  },
  {
    id: 'sustained',
    title: '소리가 계속 이어져요',
    icon: 'music',
    intro: '건반과 페달, 재생 상태를 확인해요.',
    checks: [
      '건반에서 손을 뗐는지 확인해 주세요.',
      '페달을 밟고 있는지 확인해 주세요. 연결을 임의로 바꿀 필요는 없어요.',
      '재생·아르페지오 상태인지 모르겠다면 담당자에게 확인해 주세요. 초기화·전원 차단은 안내하지 않아요.',
    ],
    control: 'rear.pedal',
  },
];
